FROM python:3.10.8-slim 

RUN git clone https://github.com/rajatgarg765/FileTrackerDjango.git

WORKDIR  "/FileTrackerDjango"

COPY . .

RUN  pip install -r requirements.txt

CMD "python manage.py runserver 127.0.0.1:8000"

EXPOSE 8000
