# Generated by Django 3.2.5 on 2022-12-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistorymodel',
            name='owners',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
